/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package labedd;

import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import javax.swing.JOptionPane;

/**
 *
 * @author jose1
 */
public class AgregarProveedor extends javax.swing.JFrame {

    /**
     * Creates new form AgregarProveedor
     */
    public AgregarProveedor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        FechaDeEntrega = new javax.swing.JTextField();
        NombreProveedor = new javax.swing.JTextField();
        CedulaJuridica = new javax.swing.JTextField();
        ProductoSuministrado = new javax.swing.JTextField();
        CantProducto = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(0, 102, 102));
        getContentPane().setLayout(null);

        jLabel1.setText("Fecha de entrega (DD/MM/AA):");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(50, 250, 190, 40);

        jLabel2.setText("AGREGA LOS PROVEDORES AQUÍ!");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(270, 10, 190, 40);

        jLabel3.setText("Nombre:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 50, 190, 40);

        jLabel4.setText("Cédula jurídica:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 100, 190, 40);

        jLabel5.setText("Producto suministrado:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(50, 150, 190, 40);

        jLabel6.setText("Cantidad del producto:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(50, 200, 190, 40);
        getContentPane().add(FechaDeEntrega);
        FechaDeEntrega.setBounds(230, 260, 200, 30);

        NombreProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreProveedorActionPerformed(evt);
            }
        });
        getContentPane().add(NombreProveedor);
        NombreProveedor.setBounds(130, 60, 300, 30);
        getContentPane().add(CedulaJuridica);
        CedulaJuridica.setBounds(150, 110, 280, 30);
        getContentPane().add(ProductoSuministrado);
        ProductoSuministrado.setBounds(190, 160, 240, 30);
        getContentPane().add(CantProducto);
        CantProducto.setBounds(190, 210, 240, 30);

        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(500, 110, 120, 150);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
           
        String Nombre = NombreProveedor.getText();
        int Cedula = Integer.parseInt(CedulaJuridica.getText());
        String ProdSuministrado= ProductoSuministrado.getText();
        int CantidadProducto = Integer.parseInt(CantProducto.getText());
        String Fecha = FechaDeEntrega.getText();
        
        // VERIFICACIONES
        if (!Nombre.matches("[a-zA-Z\\s]+")) {
        JOptionPane.showMessageDialog(this, "Por favor, ingrese un nombre válido sin números.");
        return;
    }
        // GUARDAR EN EL ARCHIVO
         try (FileWriter fw = new FileWriter("Proveedores.txt", true);
         PrintWriter pw = new PrintWriter(fw)) {
        
        pw.println("" + Nombre + "   " + Cedula + "   "  + ProdSuministrado + "   " + CantidadProducto + "   "  + Fecha );

        JOptionPane.showMessageDialog(this, "Datos guardados correctamente!");
        fw.close();

    } catch (IOException ex) {
        JOptionPane.showMessageDialog(this, "Error al guardar los datos: " + ex.getMessage());
    }
         
     
   
        
        NombreProveedor.setText("");
        CedulaJuridica.setText("");
        ProductoSuministrado.setText("");
        CantProducto.setText("");
        FechaDeEntrega.setText("");
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void NombreProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreProveedorActionPerformed
     
    }//GEN-LAST:event_NombreProveedorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarProveedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CantProducto;
    private javax.swing.JTextField CedulaJuridica;
    private javax.swing.JTextField FechaDeEntrega;
    private javax.swing.JTextField NombreProveedor;
    private javax.swing.JTextField ProductoSuministrado;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
